name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.20.2

      - name: Set up MongoDB URI
        run: echo "DB_URI=${{ secrets.DB_URI }}" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm install

      - name: Run tests
        env:
          DB_URI: ${{ secrets.DB_URI }}
        run: npm test

      - name: Build project
        run: npm run build